### ISSUE TITLE
Question: Getting it to work

### ISSUE THREAD

**Issue by egeland** [GregSutcliffe/puppet-gitolite#1]
Hi,
Great to have a module for this - just what I need.
I tried installing it, which seemed to go ok, but the user I added can't get access to the repo I set up.
In the gitolite user's $HOME, we have:

``` bash
gitolite@app1:~$ ls *
admin  admin.pub  admin-update.sh  gitolite.src.tgz  projects.list

repositories:
gitolite-admin.git  testing.git

tmp:
gitolite-admin
```

If I try to 'git clone' from the testing.git repo, I get denied (password prompted), even though I am connecting from the user whose key I put in the config in puppet:

``` bash
git clone gitolite@app1:testing.git
Cloning into 'testing'...
gitolite@app1's password:
```

Would you have any ideas of what might be wrong? A puppet run on the server doesn't have errors, and my node definition looks like:

``` puppet
node 'app1.example.com' inherits foundation {
    class { 'gitolite': }
    gitolite::repo { 'testrepo':
        auth => 'puppet:///modules/gitolite/testrepo.conf',
        keys => 'puppet:///modules/gitolite/testrepo-keys',
    }
}
```

Thanks,
Frode

**Comment by GregSutcliffe** [comment]
Glad you like it :)

If the puppet run isn't failing there's two possibilities - either your config is wrong somehow, or the gl-admin-push that the module uses internally is failing. Let's start with the easier one: can you show your testrepo.conf file and an 'ls' of your key directory?

**Comment by egeland** [comment]
testrepo.conf:

``` bash
$ cat testrepo.conf 
@ops = fegeland

repo testrepo
  RW+ = @ops
```

``` bash
$ ls -l testrepo-keys/
total 12
-rw-r--r-- 1 fegeland fegeland 733 May  9 11:44 fegeland.pub
```

And for the sake of completeness, here's how the module looks in puppet:

``` bash
$ tree
.
├── files
│   ├── admin.conf
│   ├── admin-keys
│   │   └── admin.pub
│   ├── gitolite.conf
│   ├── gitolite-rc
│   ├── gitolite.src.tgz
│   ├── testrepo.conf
│   └── testrepo-keys
│       └── fegeland.pub
├── manifests
│   ├── config.pp
│   ├── init.pp
│   ├── install.pp
│   ├── params.pp
│   └── repo.pp
├── metadata.json
├── Modulefile
├── README.md
├── spec
│   ├── spec_helper.rb
│   └── spec.opts
├── templates
│   ├── admin-update.sh.erb
│   └── post-hook
├── tests
│   ├── files
│   │   ├── admin.conf
│   │   ├── admin-keys
│   │   │   └── admin.pub
│   │   ├── external.conf
│   │   ├── puppet.conf
│   │   └── puppet-keys
│   │       └── gsutcliffe.pub
│   └── manifests
│       └── init.pp
└── TODO
```

**Comment by GregSutcliffe** [comment]
That all looks fine - damn, hoped it would be an easy one :)

Ok, here's how I troubleshoot my gitolite setup:
1. If you look in /var/lib/gitolite/tmp there should be a local checkout of the gitolite-admin repository
2. Check the local checkout matches what's in the module
   If not - something's gone funny, try deleting it and re-running puppet
3. If it's fine, try executing git status and see if you're up to date with main repo.
4. Finally, try pushing a change:
   Edit your gitolite config file (in the tmp/ checkout) and add a comment
   git add and git commit the change
   Run sudo -ugitolite /var/lib/gitolite/admin-update.sh (this is the script puppet runs to maintain the repo)
   See if there's any errors

If all of that looks fine then gitolite should be working - be sure you;re connecting with the key in the repo :)

**Comment by egeland** [comment]
Ok, so I deleted the whole /var/lib/gitolite tree on the box and ran puppet again.
That recreated it.
I tried running the admin-update.sh script, and it gave a git error of 

``` bash
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident  <gitolite@apcmsuap011.prod.f2.com.au
> not allowed
Everything up-to-date
```

So I followed the advice in the error, and added an identity for the gitolite user.
Then I re-ran the admin-update.sh, and it added the repos and keys and everything worked!
(I did need to read http://www.thebuzzmedia.com/git-tip-git-push-no-refs-in-common-and-none-specified/ to overcome the "No refs in common..." issue when pushing to the new repo, but after that, all was well)

Thanks for your assistance, and for making the module available! :-)

**Comment by GregSutcliffe** [comment]
@egeland - great news, glad you fixed it.

Out of curiosity, what OS are you running gitolite on? I'm wondering why I _don't_ get your error, since setting the git-config stuff should be necessary. It's an easy fix to the module if I can replicate it.... I'll update the README about the first push - it is indeed a bare repo.

Thanks for reporting this :)

**Comment by egeland** [comment]
The server is Ubuntu 11.04 "Natty".
I had to tweak the manifest as you had it failing on non-debian OSes.

**Comment by GregSutcliffe** [comment]
Cool, I'll try and replicate later this week. Feel free to send a pull request for the Ubuntu changes.
