### ISSUE TITLE
No content for gitolite::repo

### ISSUE THREAD

**Issue by jkmfsu** [GregSutcliffe/puppet-gitolite#3]
Currently the only way to specify a config file is via authfile which uses file's source. In my current setup I want to use a templated file. I'd like to do

```
gitolite::repo { 'puppet':
  content => template("gitolite.conf.erb"),
  keydir   => 'puppet:///modules/test/puppet-keys',
}
```

**Comment by GregSutcliffe** [comment]
Makes sense to me. Patches welcome :)
